apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
resources:
  - ../../base/namespace
  - git-pull-secret.yaml
  - age-key-secret.yaml
patches:
  - patch: |
      - op: replace
        path: /spec/url
        value: ssh://git@github.com/WilhelmSaretzki/training_k8s_fluxcd_namespace_demo.git
        # Der Nachfolgende Patch ist in der Regel nicht nötig und sollte bei euch entfernt werden
      - op: replace
        path: /spec/ref/branch
        value: main
    target:
      kind: GitRepository
      name: flux
  - patch: |
      - op: replace
        path: /spec/path
        value: ./fluxcd/local
    target:
      kind: Kustomization
      name: flux
